version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: challenge
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  challenge-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge-app
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/challenge
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run start:dev"
volumes:
  db_data: